### ISSUE TITLE
city = self.data['city_to_city'][city] KeyError: '上海市'

### ISSUE THREAD

**Issue by AIwjy94** [taishan1994/address_normalize#1]
/Users/wjy/miniconda3/bin/python3.6 /Users/wjy/Pycharm/AI/octv/address_normalize-main/address_normalize.py
Traceback (most recent call last):
  File "/Users/wjy/Pycharm/AI/octv/address_normalize-main/address_normalize.py", line 274, in <module>
    province, city, county, street, other
  File "/Users/wjy/Pycharm/AI/octv/address_normalize-main/address_normalize.py", line 101, in post_process
    city = self.data['city_to_city'][city]
KeyError: '上海市'
===========================
text= 通辽市 > 通辽经济技术开发区
省： 内蒙古自治区
市： 通辽市
区： 通辽经济技术开发区
街道： 
地址： 
===========================
[[0, 3, '秣陵街道'], [2, 3, '街道']]
===========================
text= 南京市江宁区秣陵街道胜太东路9号(江宁开发区)
省： 江苏省
市： 南京市
区： 江宁区
街道： 秣陵街道
地址： 胜太东路9号(江宁开发区)
===========================
===========================
text= 扬州市维扬路107号
省： 江苏省
市： 扬州市
区： 
街道： 
地址： 维扬路107号
===========================
===========================
text= 南京市江宁经济技术开发区将军大道139号
省： 江苏省
市： 南京市
区： 
街道： 经济技术开发区
地址： 区将军大道139号
===========================
===========================
text= 内蒙古自治区呼和浩特市金山开发区金山大街1号
省： 内蒙古自治区
市： 呼和浩特市
区： 
街道： 开发区
地址： 金山大街1号
===========================
===========================
text= 武汉市洪山区邮科院路88号
省： 湖北省
市： 武汉市
区： 洪山区
街道： 
地址： 邮科院路88号
===========================
===========================
text= 北京市海淀区北三环西路25号27号楼五层5002室
省： 北京市
市： 海淀区
区： 
街道： 
地址： 北三环西路25号27号楼五层5002室
===========================
===========================
text= 广州市天河区中山大道西109号大院自编1号楼14楼(仅限办公用途)
省： 广东省
市： 广州市
区： 天河区
街道： 
地址： 中山大道西109号大院自编1号楼14楼(仅限办公用途)
===========================
===========================
text= 上海市吴中路578号
省： 上海市
市： 
区： 
街道： 
地址： 吴中路578号
===========================
[[4, 7, '大浪街道'], [6, 7, '街道']]
===========================
text= 深圳市龙华新区大浪街道华宁路8号明君工业区C栋6楼
省： 广东省
市： 深圳市
区： 龙华区
街道： 大浪街道
地址： 道华宁路8号明君工业区C栋6楼
===========================

进程已结束,退出代码1

大佬、测试的时候怎么少了 '上海市青浦区赵巷镇嘉松中路5399号3幢4楼E区499室', '佛山市文沙路16号', 这两句
而且报错

**Comment by taishan1994** [comment]
> # /Users/wjy/miniconda3/bin/python3.6 /Users/wjy/Pycharm/AI/octv/address_normalize-main/address_normalize.py
> Traceback (most recent call last):
> File "/Users/wjy/Pycharm/AI/octv/address_normalize-main/address_normalize.py", line 274, in
> province, city, county, street, other
> File "/Users/wjy/Pycharm/AI/octv/address_normalize-main/address_normalize.py", line 101, in post_process
> city = self.data['city_to_city'][city]
> KeyError: '上海市'
> # text= 通辽市 > 通辽经济技术开发区
> 省： 内蒙古自治区
> 市： 通辽市
> 区： 通辽经济技术开发区
> 街道：
> 地址：
> # [[0, 3, '秣陵街道'], [2, 3, '街道']]
> # text= 南京市江宁区秣陵街道胜太东路9号(江宁开发区)
> 省： 江苏省
> 市： 南京市
> 区： 江宁区
> 街道： 秣陵街道
> 地址： 胜太东路9号(江宁开发区)
> # ===========================
> text= 扬州市维扬路107号
> 省： 江苏省
> 市： 扬州市
> 区：
> 街道：
> 地址： 维扬路107号
> # ===========================
> text= 南京市江宁经济技术开发区将军大道139号
> 省： 江苏省
> 市： 南京市
> 区：
> 街道： 经济技术开发区
> 地址： 区将军大道139号
> # ===========================
> text= 内蒙古自治区呼和浩特市金山开发区金山大街1号
> 省： 内蒙古自治区
> 市： 呼和浩特市
> 区：
> 街道： 开发区
> 地址： 金山大街1号
> # ===========================
> text= 武汉市洪山区邮科院路88号
> 省： 湖北省
> 市： 武汉市
> 区： 洪山区
> 街道：
> 地址： 邮科院路88号
> # ===========================
> text= 北京市海淀区北三环西路25号27号楼五层5002室
> 省： 北京市
> 市： 海淀区
> 区：
> 街道：
> 地址： 北三环西路25号27号楼五层5002室
> # ===========================
> text= 广州市天河区中山大道西109号大院自编1号楼14楼(仅限办公用途)
> 省： 广东省
> 市： 广州市
> 区： 天河区
> 街道：
> 地址： 中山大道西109号大院自编1号楼14楼(仅限办公用途)
> # ===========================
> text= 上海市吴中路578号
> 省： 上海市
> 市：
> 区：
> 街道：
> 地址： 吴中路578号
> # [[4, 7, '大浪街道'], [6, 7, '街道']]
> # text= 深圳市龙华新区大浪街道华宁路8号明君工业区C栋6楼
> 省： 广东省
> 市： 深圳市
> 区： 龙华区
> 街道： 大浪街道
> 地址： 道华宁路8号明君工业区C栋6楼
> 进程已结束,退出代码1
> 
> 大佬、测试的时候怎么少了 '上海市青浦区赵巷镇嘉松中路5399号3幢4楼E区499室', '佛山市文沙路16号', 这两句 而且报错

报了个错，修改了下数据，重新下载份。
